export const ADD_USER_AS_FRIEND = 'ADD_FRIEND';
export const REMOVE_USER_AS_FRIEND = 'REMOVE_FRIEND';

export const ADD_A_WISHLIST = 'ADD_WISHLIST';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_MULTIPLE_TO_WISHLIST = 'ADD_MULTIPLE_TO_WISHLIST';
export const SORT_WISHLIST_ALPHABETICALLY = 'SORT_WISHLIST_ALPHABETICALLY';
export const SORT_WISHLIST_PRICE_ASC = 'SORT_WISHLIST_PRICE_ASC';
export const SORT_WISHLIST_PRICE_DESC = 'SORT_WISHLIST_PRICE_DESC';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const ADD_TO_SECRET_LIST = 'ADD_TO_SECRET_LIST';
export const ADD_MULTIPLE_TO_SECRET_LIST = 'ADD_MULTIPLE_TO_SECRET_LIST';
export const SORT_SECRET_LIST_ALPHABETICALLY = 'SORT_SECRET_LIST_ALPHABETICALLY';
export const SORT_SECRET_LIST_PRICE_ASC = 'SORT_SECRET_LIST_PRICE_ASC';
export const SORT_SECRET_LIST_PRICE_DESC = 'SORT_SECRET_LIST_PRICE_DESC';
export const UPDATE_SECRET_LIST_ITEM = 'UPDATE_SECRET_LIST_ITEM';
export const REMOVE_FROM_SECRET_LIST = 'REMOVE_FROM_SECRET_LIST';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const ADD_MULTIPLE_TO_SHOPPING_LIST = 'ADD_MULTIPLE_TO_SHOPPING_LIST';
export const UPDATE_SHOPPING_LIST_ITEM = 'UPDATE_SHOPPING_LIST_ITEM';
export const REMOVE_FROM_SHOPPING_LIST = 'REMOVE_FROM_SHOPPING_LIST';
