export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_MULTIPLE_TO_WISHLIST = 'ADD_MULTIPLE_TO_WISHLIST';
export const UPDATE_WISHLIST_ITEM = 'UPDATE_WISHLIST_ITEM';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';

export const ADD_TO_SECRET_LIST = 'ADD_TO_SECRET_LIST';
export const ADD_MULTIPLE_TO_SECRET_LIST = 'ADD_MULTIPLE_TO_SECRET_LIST';
export const UPDATE_SECRET_LIST_ITEM = 'UPDATE_SECRET_LIST_ITEM';
export const REMOVE_FROM_SECRET_LIST = 'REMOVE_FROM_SECRET_LIST';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const ADD_MULTIPLE_TO_SHOPPING_LIST = 'ADD_MULTIPLE_TO_SHOPPING_LIST';
export const UPDATE_SHOPPING_LIST_ITEM = 'UPDATE_SHOPPING_LIST_ITEM';
export const REMOVE_FROM_SHOPPING_LIST = 'REMOVE_FROM_SHOPPING_LIST';
