export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const ADD_MULTIPLE_TO_WISHLIST = 'ADD_MULTIPLE_TO_WISHLIST';

export const ADD_TO_SECRET_LIST = 'ADD_TO_SECRET_LIST';
export const ADD_MULTIPLE_TO_SECRET_LIST = 'ADD_MULTIPLE_TO_SECRET_LIST';
export const UPDATE_SECRET_LIST_ITEM = 'UPDATE_SECRET_LIST_ITEM';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const ADD_MULTIPLE_TO_SHOPPING_LIST = 'ADD_MULTIPLE_TO_SHOPPING_LIST';
